service: aws-reaper-lambda

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Actions:
        - "ec2:DescribeVolumes"
        - "ec2:DeleteVolume"

functions:
  hello:
    handler: handler.reaper
    events:
      - schedule: rate(1 day)
