service: aws-reaper-lambda

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeVolumes"
        - "ec2:DeleteVolume"
      Resource:
        - "*"

functions:
  ebs-reaper:
    handler: handler.reaper
    events:
      - schedule: rate(1 day)
